language: ruby
sudo: false

rvm:
  - 2.3.1

gemfile:
  - Gemfile

env:
  - CHEF_VERSION=master
  - CHEF_VERSION=12.17
  - CHEF_VERSION=12.5
  - CHEF_VERSION=12

before_script:
  - bundle exec berks

script:
  - bundle exec foodcritic -f any .
  - bundle exec rspec
